version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
      - npm run test
  build:
    commands:
      - npm run build:$STAGE
  post_build:
    commands:
      - npm run publish:$STAGE
artifacts:
  files:
    - "**/*"
  base-directory: "src"
